// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.14.0
// source: ValidationService/infrastructure/cartServiceClient/api/CartService.proto

package CartServiceApiPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint64                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{0}
}

func (x *AddToCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToCartRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddToCartRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint64                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteItemRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteItemRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{2}
}

func (x *ClearCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{4}
}

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    uint64                 `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP(), []int{5}
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartResponse) GetTotalPrice() uint64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_ValidationService_infrastructure_cartServiceClient_api_CartService_proto protoreflect.FileDescriptor

const file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDesc = "" +
	"\n" +
	"HValidationService/infrastructure/cartServiceClient/api/CartService.proto\x12\x04cart\"X\n" +
	"\x10AddToCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x04R\x05skuId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"C\n" +
	"\x11DeleteItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x04R\x05skuId\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"a\n" +
	"\bCartItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\"X\n" +
	"\x0fGetCartResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.cart.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x04R\n" +
	"totalPrice2\xfb\x01\n" +
	"\vCartService\x12:\n" +
	"\tAddToCart\x12\x16.cart.AddToCartRequest\x1a\x15.cart.GetCartResponse\x12<\n" +
	"\n" +
	"DeleteItem\x12\x17.cart.DeleteItemRequest\x1a\x15.cart.GetCartResponse\x12:\n" +
	"\tClearCart\x12\x16.cart.ClearCartRequest\x1a\x15.cart.GetCartResponse\x126\n" +
	"\aGetCart\x12\x14.cart.GetCartRequest\x1a\x15.cart.GetCartResponseB7Z5infrastructure/cartServiceClient/api/CartServiceApiPbb\x06proto3"

var (
	file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescOnce sync.Once
	file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescData []byte
)

func file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescGZIP() []byte {
	file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescOnce.Do(func() {
		file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDesc), len(file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDesc)))
	})
	return file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDescData
}

var file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_goTypes = []any{
	(*AddToCartRequest)(nil),  // 0: cart.AddToCartRequest
	(*DeleteItemRequest)(nil), // 1: cart.DeleteItemRequest
	(*ClearCartRequest)(nil),  // 2: cart.ClearCartRequest
	(*GetCartRequest)(nil),    // 3: cart.GetCartRequest
	(*CartItem)(nil),          // 4: cart.CartItem
	(*GetCartResponse)(nil),   // 5: cart.GetCartResponse
}
var file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_depIdxs = []int32{
	4, // 0: cart.GetCartResponse.items:type_name -> cart.CartItem
	0, // 1: cart.CartService.AddToCart:input_type -> cart.AddToCartRequest
	1, // 2: cart.CartService.DeleteItem:input_type -> cart.DeleteItemRequest
	2, // 3: cart.CartService.ClearCart:input_type -> cart.ClearCartRequest
	3, // 4: cart.CartService.GetCart:input_type -> cart.GetCartRequest
	5, // 5: cart.CartService.AddToCart:output_type -> cart.GetCartResponse
	5, // 6: cart.CartService.DeleteItem:output_type -> cart.GetCartResponse
	5, // 7: cart.CartService.ClearCart:output_type -> cart.GetCartResponse
	5, // 8: cart.CartService.GetCart:output_type -> cart.GetCartResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_init() }
func file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_init() {
	if File_ValidationService_infrastructure_cartServiceClient_api_CartService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDesc), len(file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_goTypes,
		DependencyIndexes: file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_depIdxs,
		MessageInfos:      file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_msgTypes,
	}.Build()
	File_ValidationService_infrastructure_cartServiceClient_api_CartService_proto = out.File
	file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_goTypes = nil
	file_ValidationService_infrastructure_cartServiceClient_api_CartService_proto_depIdxs = nil
}
