// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/verbovyar/OzonCart/internal/service.ClientIface -o client_iface_mock.go -n ClientIfaceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	mm_service "github.com/verbovyar/OzonCart/internal/service"
)

// ClientIfaceMock implements mm_service.ClientIface
type ClientIfaceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetProduct          func(ctx context.Context, sku uint64) (pp1 *mm_service.Product, err error)
	funcGetProductOrigin    string
	inspectFuncGetProduct   func(ctx context.Context, sku uint64)
	afterGetProductCounter  uint64
	beforeGetProductCounter uint64
	GetProductMock          mClientIfaceMockGetProduct
}

// NewClientIfaceMock returns a mock for mm_service.ClientIface
func NewClientIfaceMock(t minimock.Tester) *ClientIfaceMock {
	m := &ClientIfaceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductMock = mClientIfaceMockGetProduct{mock: m}
	m.GetProductMock.callArgs = []*ClientIfaceMockGetProductParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mClientIfaceMockGetProduct struct {
	optional           bool
	mock               *ClientIfaceMock
	defaultExpectation *ClientIfaceMockGetProductExpectation
	expectations       []*ClientIfaceMockGetProductExpectation

	callArgs []*ClientIfaceMockGetProductParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ClientIfaceMockGetProductExpectation specifies expectation struct of the ClientIface.GetProduct
type ClientIfaceMockGetProductExpectation struct {
	mock               *ClientIfaceMock
	params             *ClientIfaceMockGetProductParams
	paramPtrs          *ClientIfaceMockGetProductParamPtrs
	expectationOrigins ClientIfaceMockGetProductExpectationOrigins
	results            *ClientIfaceMockGetProductResults
	returnOrigin       string
	Counter            uint64
}

// ClientIfaceMockGetProductParams contains parameters of the ClientIface.GetProduct
type ClientIfaceMockGetProductParams struct {
	ctx context.Context
	sku uint64
}

// ClientIfaceMockGetProductParamPtrs contains pointers to parameters of the ClientIface.GetProduct
type ClientIfaceMockGetProductParamPtrs struct {
	ctx *context.Context
	sku *uint64
}

// ClientIfaceMockGetProductResults contains results of the ClientIface.GetProduct
type ClientIfaceMockGetProductResults struct {
	pp1 *mm_service.Product
	err error
}

// ClientIfaceMockGetProductOrigins contains origins of expectations of the ClientIface.GetProduct
type ClientIfaceMockGetProductExpectationOrigins struct {
	origin    string
	originCtx string
	originSku string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProduct *mClientIfaceMockGetProduct) Optional() *mClientIfaceMockGetProduct {
	mmGetProduct.optional = true
	return mmGetProduct
}

// Expect sets up expected params for ClientIface.GetProduct
func (mmGetProduct *mClientIfaceMockGetProduct) Expect(ctx context.Context, sku uint64) *mClientIfaceMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ClientIfaceMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.paramPtrs != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by ExpectParams functions")
	}

	mmGetProduct.defaultExpectation.params = &ClientIfaceMockGetProductParams{ctx, sku}
	mmGetProduct.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetProduct.expectations {
		if minimock.Equal(e.params, mmGetProduct.defaultExpectation.params) {
			mmGetProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProduct.defaultExpectation.params)
		}
	}

	return mmGetProduct
}

// ExpectCtxParam1 sets up expected param ctx for ClientIface.GetProduct
func (mmGetProduct *mClientIfaceMockGetProduct) ExpectCtxParam1(ctx context.Context) *mClientIfaceMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ClientIfaceMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &ClientIfaceMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetProduct.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetProduct
}

// ExpectSkuParam2 sets up expected param sku for ClientIface.GetProduct
func (mmGetProduct *mClientIfaceMockGetProduct) ExpectSkuParam2(sku uint64) *mClientIfaceMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ClientIfaceMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &ClientIfaceMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.sku = &sku
	mmGetProduct.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmGetProduct
}

// Inspect accepts an inspector function that has same arguments as the ClientIface.GetProduct
func (mmGetProduct *mClientIfaceMockGetProduct) Inspect(f func(ctx context.Context, sku uint64)) *mClientIfaceMockGetProduct {
	if mmGetProduct.mock.inspectFuncGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("Inspect function is already set for ClientIfaceMock.GetProduct")
	}

	mmGetProduct.mock.inspectFuncGetProduct = f

	return mmGetProduct
}

// Return sets up results that will be returned by ClientIface.GetProduct
func (mmGetProduct *mClientIfaceMockGetProduct) Return(pp1 *mm_service.Product, err error) *ClientIfaceMock {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ClientIfaceMockGetProductExpectation{mock: mmGetProduct.mock}
	}
	mmGetProduct.defaultExpectation.results = &ClientIfaceMockGetProductResults{pp1, err}
	mmGetProduct.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// Set uses given function f to mock the ClientIface.GetProduct method
func (mmGetProduct *mClientIfaceMockGetProduct) Set(f func(ctx context.Context, sku uint64) (pp1 *mm_service.Product, err error)) *ClientIfaceMock {
	if mmGetProduct.defaultExpectation != nil {
		mmGetProduct.mock.t.Fatalf("Default expectation is already set for the ClientIface.GetProduct method")
	}

	if len(mmGetProduct.expectations) > 0 {
		mmGetProduct.mock.t.Fatalf("Some expectations are already set for the ClientIface.GetProduct method")
	}

	mmGetProduct.mock.funcGetProduct = f
	mmGetProduct.mock.funcGetProductOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// When sets expectation for the ClientIface.GetProduct which will trigger the result defined by the following
// Then helper
func (mmGetProduct *mClientIfaceMockGetProduct) When(ctx context.Context, sku uint64) *ClientIfaceMockGetProductExpectation {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ClientIfaceMock.GetProduct mock is already set by Set")
	}

	expectation := &ClientIfaceMockGetProductExpectation{
		mock:               mmGetProduct.mock,
		params:             &ClientIfaceMockGetProductParams{ctx, sku},
		expectationOrigins: ClientIfaceMockGetProductExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetProduct.expectations = append(mmGetProduct.expectations, expectation)
	return expectation
}

// Then sets up ClientIface.GetProduct return parameters for the expectation previously defined by the When method
func (e *ClientIfaceMockGetProductExpectation) Then(pp1 *mm_service.Product, err error) *ClientIfaceMock {
	e.results = &ClientIfaceMockGetProductResults{pp1, err}
	return e.mock
}

// Times sets number of times ClientIface.GetProduct should be invoked
func (mmGetProduct *mClientIfaceMockGetProduct) Times(n uint64) *mClientIfaceMockGetProduct {
	if n == 0 {
		mmGetProduct.mock.t.Fatalf("Times of ClientIfaceMock.GetProduct mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProduct.expectedInvocations, n)
	mmGetProduct.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetProduct
}

func (mmGetProduct *mClientIfaceMockGetProduct) invocationsDone() bool {
	if len(mmGetProduct.expectations) == 0 && mmGetProduct.defaultExpectation == nil && mmGetProduct.mock.funcGetProduct == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProduct.mock.afterGetProductCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProduct.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProduct implements mm_service.ClientIface
func (mmGetProduct *ClientIfaceMock) GetProduct(ctx context.Context, sku uint64) (pp1 *mm_service.Product, err error) {
	mm_atomic.AddUint64(&mmGetProduct.beforeGetProductCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProduct.afterGetProductCounter, 1)

	mmGetProduct.t.Helper()

	if mmGetProduct.inspectFuncGetProduct != nil {
		mmGetProduct.inspectFuncGetProduct(ctx, sku)
	}

	mm_params := ClientIfaceMockGetProductParams{ctx, sku}

	// Record call args
	mmGetProduct.GetProductMock.mutex.Lock()
	mmGetProduct.GetProductMock.callArgs = append(mmGetProduct.GetProductMock.callArgs, &mm_params)
	mmGetProduct.GetProductMock.mutex.Unlock()

	for _, e := range mmGetProduct.GetProductMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProduct.GetProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProduct.GetProductMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProduct.GetProductMock.defaultExpectation.params
		mm_want_ptrs := mmGetProduct.GetProductMock.defaultExpectation.paramPtrs

		mm_got := ClientIfaceMockGetProductParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetProduct.t.Errorf("ClientIfaceMock.GetProduct got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmGetProduct.t.Errorf("ClientIfaceMock.GetProduct got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProduct.t.Errorf("ClientIfaceMock.GetProduct got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProduct.GetProductMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProduct.t.Fatal("No results are set for the ClientIfaceMock.GetProduct")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProduct.funcGetProduct != nil {
		return mmGetProduct.funcGetProduct(ctx, sku)
	}
	mmGetProduct.t.Fatalf("Unexpected call to ClientIfaceMock.GetProduct. %v %v", ctx, sku)
	return
}

// GetProductAfterCounter returns a count of finished ClientIfaceMock.GetProduct invocations
func (mmGetProduct *ClientIfaceMock) GetProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.afterGetProductCounter)
}

// GetProductBeforeCounter returns a count of ClientIfaceMock.GetProduct invocations
func (mmGetProduct *ClientIfaceMock) GetProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.beforeGetProductCounter)
}

// Calls returns a list of arguments used in each call to ClientIfaceMock.GetProduct.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProduct *mClientIfaceMockGetProduct) Calls() []*ClientIfaceMockGetProductParams {
	mmGetProduct.mutex.RLock()

	argCopy := make([]*ClientIfaceMockGetProductParams, len(mmGetProduct.callArgs))
	copy(argCopy, mmGetProduct.callArgs)

	mmGetProduct.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductDone returns true if the count of the GetProduct invocations corresponds
// the number of defined expectations
func (m *ClientIfaceMock) MinimockGetProductDone() bool {
	if m.GetProductMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductMock.invocationsDone()
}

// MinimockGetProductInspect logs each unmet expectation
func (m *ClientIfaceMock) MinimockGetProductInspect() {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientIfaceMock.GetProduct at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetProductCounter := mm_atomic.LoadUint64(&m.afterGetProductCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && afterGetProductCounter < 1 {
		if m.GetProductMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ClientIfaceMock.GetProduct at\n%s", m.GetProductMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ClientIfaceMock.GetProduct at\n%s with params: %#v", m.GetProductMock.defaultExpectation.expectationOrigins.origin, *m.GetProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && afterGetProductCounter < 1 {
		m.t.Errorf("Expected call to ClientIfaceMock.GetProduct at\n%s", m.funcGetProductOrigin)
	}

	if !m.GetProductMock.invocationsDone() && afterGetProductCounter > 0 {
		m.t.Errorf("Expected %d calls to ClientIfaceMock.GetProduct at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductMock.expectedInvocations), m.GetProductMock.expectedInvocationsOrigin, afterGetProductCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClientIfaceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetProductInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClientIfaceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClientIfaceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductDone()
}
